### ISSUE TITLE
ATS-extsolve

### ISSUE THREAD

**Issue by sheganinans** [githwxi/ATS-Postiats-contrib#35]
@wdblair Awesome project! But I get this error:

> cd ~/Projects/github/ATS-Postiats-contrib/contrib/libats-/wdblair/prelude/
> patsopt --constraint-export -tc -d TEST/quicksort.dats | patsolve
exit(ATS): unmatched value at run-time:
/tmp/nix-build-ats-extsolve-0pre6a9b752.drv-0/ATS-Postiats-contrib-6a9b752efb8af1e4f77213f9e81fc2b7fa050877/projects/MEDIUM/ATS-extsolve/parsing/parsing_c3nstr.dats: 479(line=37, offs=5) -- 536(line=38, offs=41)

**Comment by wdblair** [comment]
Hi Aistis,

Thanks for your interest in the project! I need to open up a pull request for this repo, since the code here is out of date. The format of exported constraints has changed since this earlier version so parsing in patsolve will always crash. A much more up to date version of ATS-extsolve can be found at my fork of the repo:

    https://github.com/wdblair/ATS-Postiats-contrib/tree/master/projects/MEDIUM/ATS-extsolve

There are more examples there for you to work with in the contrib folder there as well

    https://github.com/wdblair/ATS-Postiats-contrib/tree/master/contrib/libats-/wdblair/prelude/TEST

Then I have a webpage set up that describes how to use the external constraint solver.

    http://www.illtyped.com/projects/patsolve/

Since working with two different contrib folders might be messy, I'll try to get a pull request in soon so you can run it from the official repo :D 

Thanks,
Will

**Comment by sheganinans** [comment]
Excellent thanks! I noticed that you had some additional contributions in
your fork. I'll await until they have been merged. Thanks!

**Comment by githwxi** [comment]
Patsolve is an extremely useful extension for ATS. I plan to work with Will during the next two weeks
to get it merged so that we could soon have an "official" version :)

**Comment by sheganinans** [comment]
Hongwei, I am very excited about this! Having Z3 integrated seems like a
massive win for ATS! I'll be holding my breath for the release! Hopefully
my face doesn't turn too blue.

**Comment by shlevy** [comment]
@githwxi Did you mean you will work on getting the changes merged into this contrib repo, or that patsolve will become part of ATS-Postiats itself?

**Comment by githwxi** [comment]
Patsolve is planned to stay in ATS2-contrib.

**Comment by shlevy** [comment]
Seems to be fixed now in master, right?

**Comment by githwxi** [comment]
Yes, I have pulled in Will's patsolve code.

**Comment by githwxi** [comment]
I just want to say that I am still working on ATSS-extsolve:

https://github.com/githwxi/ATS-Postiats-contrib/tree/master/projects/MEDIUM/ATS-extsolve
https://github.com/githwxi/ATS-Postiats-contrib/tree/master/projects/MEDIUM/ATS-extsolve-z3

ATS-extsolve-z3 is for using Z3 to solve ATS-constrants. It is not yet functioning but will be soon. However,
in order to make good use of the power of Z3, there is still a long way to go. Of course, one needs to have a good knowledge of Z3 as well. Keep tuned.

**Comment by master-q** [comment]
ATS-extsolve-z3 has error?

```
$ pwd
/home/kiwamu/src/ATS-Postiats-contrib/projects/MEDIUM/ATS-extsolve-z3
$ make
"/home/kiwamu/src/ATS-Postiats"/bin/patscc  -DATS_MEMALLOC_LIBC -I/home/kiwamu/src/ATS-Postiats-contrib/contrib -I/home/kiwamu/src/ATS-Postiats-contrib/contrib/SMT -I/usr/include/json-c  -c patsolve_z3_main.dats
/home/kiwamu/src/ATS-Postiats-contrib/projects/MEDIUM/ATS-extsolve-z3/patsolve_z3_solving.sats: 317(line=25, offs=1) -- 360(line=25, offs=44): error(1): the file [{$PATSOLVE}/patsolve_cnstrnt.sats] is not available for staloading.
patsopt(TRANS1): there are [1] errors in total.
exit(ATS): uncaught exception: _2home_2kiwamu_2src_2ATS_2dPostiats_2src_2pats_error_2esats__FatalErrorExn(1025)
Makefile:124: recipe for target 'patsolve_z3_main_dats.o' failed
make: *** [patsolve_z3_main_dats.o] Error 1
```

**Comment by githwxi** [comment]
You need to do the following first:

make -C /home/kiwamu/src/ATS-Postiats-contrib/projects/MEDIUM/ATS-extsolve DATS_C

**Comment by master-q** [comment]
Not yet fix...

```
$ make -C /home/kiwamu/src/ATS-Postiats-contrib/projects/MEDIUM/ATS-extsolve DATS_C
make: Entering directory '/home/kiwamu/src/ATS-Postiats-contrib/projects/MEDIUM/ATS-extsolve'
\
"/home/kiwamu/src/ATS-Postiats"/bin/patsopt -o CATS/patsolve_cnstrnt_dats.c --dynamic patsolve_cnstrnt.dats
\
"/home/kiwamu/src/ATS-Postiats"/bin/patsopt -o CATS/patsolve_parsing_dats.c --dynamic patsolve_parsing.dats
make: Leaving directory '/home/kiwamu/src/ATS-Postiats-contrib/projects/MEDIUM/ATS-extsolve'
$ make
"/home/kiwamu/src/ATS-Postiats"/bin/patscc  -DATS_MEMALLOC_LIBC -I/home/kiwamu/src/ATS-Postiats-contrib/contrib -I/home/kiwamu/src/ATS-Postiats-contrib/contrib/SMT -I/usr/include/json-c  -c patsolve_z3_main.dats
/home/kiwamu/src/ATS-Postiats-contrib/projects/MEDIUM/ATS-extsolve-z3/patsolve_z3_solving.sats: 317(line=25, offs=1) -- 360(line=25, offs=44): error(1): the file [{$PATSOLVE}/patsolve_cnstrnt.sats] is not available for staloading.
patsopt(TRANS1): there are [1] errors in total.
exit(ATS): uncaught exception: _2home_2kiwamu_2src_2ATS_2dPostiats_2src_2pats_error_2esats__FatalErrorExn(1025)
Makefile:124: recipe for target 'patsolve_z3_main_dats.o' failed
make: *** [patsolve_z3_main_dats.o] Error 1
```

**Comment by githwxi** [comment]
Try 'make build'

**Comment by master-q** [comment]
FIx it. Is it documented?

**Comment by githwxi** [comment]
Kind of.

This is the script for building various ATS packages:

https://gist.github.com/githwxi/7e31f4fd4df92125b73c

**Comment by master-q** [comment]
How about put ATS-Postiats-contrib/projects/MEDIUM/ATS-extsolve-z3/README that include following:

```
$ make -C ../ATS-extsolve DATS_C
$ make build
```

**Comment by githwxi** [comment]
WIll do. I am in the middle of improving patsolve_z3 right now.
